#玩家发出的聊天信息格式: '<类型><插件> <功能> [变量,...]'
#类型: '/f '代表命令类型,'$'代表物品类型,'#'代表聊天类型
#插件: 插件名(类似命名空间,给功能分组的)
#功能: 程序自定义的功能名

#################################
#####         语言          #####
#################################
lang:
  cn: "lang_cn.yml"

#################################
#####      功能提示符       #####
#################################
#如果玩家的聊天信息以此为前缀,则表明玩家打算执行对应的功能
symbol:
  cmd: "/f "
  item: "$"
  chat: "#"